server:
  port: 8080

spring:
  application:
    name: auth-api
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
app:
  jwt:
    secret: ${JWT_SECRET:4fdH334jj8kjf40n3hd3jdkejd322kdnj32n2dnjsd2f4b}
    expiration-ms: 76000
  internal-token: ${INTERNAL_TOKEN:dev-internal-token}
  data-api-url: ${DATA_API_URL:http://data-api:8081}
